const ITEMS_FETCHING = 'ITEMS_FETCHING',
  ITEMS_FETCHED = 'ITEMS_FETCHED',
  ACTIVE_ITEM_UPDATED = 'ACTIVE_ITEM_UPDATED',
  FAILED_FETCH = 'FAILED_FETCH';

export { ITEMS_FETCHING, ITEMS_FETCHED, ACTIVE_ITEM_UPDATED, FAILED_FETCH };
